apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseActiveActiveDatabase
metadata:
  name: crdb-anton
spec:
  globalConfigurations:
    #databaseSecretName: crdb-anton
    memorySize: 200MB
    shardCount: 1
    replication: true
  participatingClusters:
      - name: CLUSTER1
      - name: CLUSTER2
